  server:
    port: 8080
  spring:
      datasource:
          url: jdbc:mysql://localhost:3306/lyli?characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: root
          password: 120310jk
      jpa:
        properties:
          hibernate:
            show_sql: true
            format_sql: true

